<div class="PostContainer" data-path="/<?= "$post->section_slug/$post->slug" ?>" data-title="<?= $post->title ?>">
  <div class="PostContainer-leftCol">
    <article class="Post">
      <? include partial('post/admin_buttons') ?>
      <h1 class="Post-title">
        <?= $post->title ?>
      </h1>
      <div class="Content">
        <?= $post->html_content() ?>
      </div>
    </article>
  </div>
  <div class="PostContainer-rightCol">
    <? include partial('post/links') ?>
  </div>
</div>
