<div class="PostLinks">
  <p class="PostLinks-title">
    more posts
  </p>
  <a class="PostLinks-link" href="/post.php">
    Other post link goes here
  </a>
  <a class="PostLinks-link is-current" href="/post.php">
    this is the current post
  </a>
  <a class="PostLinks-link" href="/post.php">
    this is a third post
  </a>
  <a class="PostLinks-link" href="/post.php">
    and finally this
  </a>
</div>