<section class="About" data-path="/about" data-title="About Me">
  <h1 class="About-title">About Me</h1>
  <div class="About-frame">
    <img class="About-image" src="https://i.imgur.com/uGdFBKY.jpg">
    <div class="About-content">
      <div class="Content">

        <p>I'm a web and mobile developer working in Brighton UK.</p>
        <p>I currently work at <a href="http://activeinboxhq.com">Active Inbox</a>, on our core product and engaging with our active community of users.</p>
        <p>I have worked with</p>
        <ul>
          <li>Ruby on Rails</li>
          <li>PHP (both pure and various CMSs)</li>
          <li>JavaScript (ES5 &amp; ES2015)</li>
          <li>Objective C</li>
          <li>Swift</li>
        </ul>
        <p>In my previous job at <a href="http://thisishatch.co.uk">Hatch</a> I worked on various client projects, ranging from small websites like <a href="http://menuhin.org">menuhin.org</a> to location aware mobile apps using iBeacons.</p>
        <p>You can check out my <a href="https://github.com/RShergold">GitHub</a> or <script>document.write("<a href='mailto:" + atob('cmVtaS5zaGVyZ29sZEBnbWFpbC5jb20=') + "'>email me</a>")</script></p>

      </div>
    </div>
  </div>
</section>
