
  <div class="PageContainer">
    <div class="PageContainer-sideBar" id="js-stickySidebar">
      <div class="SideNav" >
        <a class="SideNav-title" href="/">
          Remi<br>Shergold
        </a>
        <? foreach (Nav::$sections as $nav_section): ?>
          <a class="SideNav-link <? if ($nav_section->is_current()) echo 'is-current' ?>" href="/<?= $nav_section->slug ?>">
            <?= $nav_section->name ?>
          </a>
        <? endforeach; ?>
        <a class="SideNav-link <?= ($_SERVER['REQUEST_URI'] == '/about') ? 'is-current' : '' ?>" href="/about">About Me</a>
      </div>
    </div>
    <div class="PageContainer-content">
