  <div class="PageContainer">
    <div class="PageContainer-sideBar" id="js-stickySidebar">
      <div class="SideNav" >
        <a class="SideNav-title" href="/">
          Remi<br>Shergold
        </a>
        <a class="SideNav-link" href="#">Projects</a>
        <a class="SideNav-link is-current" href="#">Scrapbook</a>
        <a class="SideNav-link" href="#">About Me</a>
      </div>
    </div>
    <div class="PageContainer-content">
