      <div class="IndexPage">
        <h1 class="IndexPage-title">
          Title here
        </h1>
        <p class="IndexPage-discription">
          Some of my small personal projects. You can also find a few other bits and 
          peices on my <a class="Link" href="#">GitHub</a> page
        </p>
        <div class="IndexPage-panelContainer">
          <article class="Panel Panel--withImage">
            <a class="Panel-link" href="#">
              <img class="Panel-image" src="http://placehold.it/280x145">
              <div class="Panel-copy">
                <h1 class="Panel-title">title here</h1>
                lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
              </div>
            </a>
          </article>
          
          <article class="Panel Panel--withImage">
            <a class="Panel-link" href="#">
              <img class="Panel-image" src="http://placehold.it/280x145">
              <div class="Panel-copy">
                <h1 class="Panel-title">title here</h1>
                lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
              </div>
            </a>
          </article>
          
          <article class="Panel">
            <a class="Panel-link" href="#">
              <div class="Panel-copy">
                <h1 class="Panel-title">title here</h1>
                lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
              </div>
            </a>
          </article>
        </div>
      </div>