<section class="IndexPage" data-path="/<?= $section->slug ?>" data-title="<?= $section->title ?>">
  <h1 class="IndexPage-title">
    <?= $section->title ?>
  </h1>
  <p class="IndexPage-discription">
    <?= $section->description ?>
  </p>
  <div class="IndexPage-panelContainer">
    <? foreach($section->pages as $page): ?>
      <? include partial('section/panel') ?>
    <? endforeach; ?>
  </div>
</section>