<article class="Panel <?= $page->panel_type ?>">
  <a class="Panel-link" href="<?= $page->src() ?>">
    <? if ($page->image_path): ?>
     <!--
     <figure class="Panel-image" style="background-image:url('<?= $page->image_path ?>')"></figure>
     -->
     <img class="Panel-image" src="<?= $page->image_path ?>">
    <? endif ?>
    <div class="Panel-copy">
      <h1 class="Panel-title"><?= $page->title ?></h1>
      <?= $page->description ?>
    </div>
  </a>
</article>
