
<form class="PostContainer" method="post" id="js-inputForm">

  <input type="hidden" name="action" value="save">
  <? if (!NEW_POST): ?><input type="hidden" name="id" value="<?= $post->id ?>" ><? endif; ?>

  <div class="PostContainer-leftCol">
    <article class="Input is-showing-markdown" id="js-inputFrame">
    <? include partial('input/toolbar') ?>
      <textarea id="js-title" class="Input-title" placeholder="Title" name="title" data-min-height="70"><?= $post->title ?></textarea>
      <i class="Input-hr"></i>
      <textarea id="js-markdown" class="Input-markdown" name="content" data-min-height="320"><?= $post->content ?></textarea>
      <div id="js-preview" class="Input-preview Content"><?= $post->html_content() ?></div>
      <textarea class="Input-description" name="description" data-min-height="96"><?= $post->description ?></textarea>
    </article>
  </div>

  <div class="PostContainer-rightCol">
    <? include partial('input/files') ?>
  </div>

  <input class="SaveButton" type="submit" value="Save">

</form>
