<li class="SingleFile">
  <button class="SingleFile-delete">X</button>
  <img class="SingleFile-image" src="http://lorempixel.com/image_output/fashion-q-c-198-136-6.jpg">
  <p class="SingleFile-title">
    name-of-image-here.png
  </p>
</li>

<li class="SingleFile SingleFile--titleOnly">
  <button class="SingleFile-delete">X</button>
  <p class="SingleFile-title">
    name-of-file.txt
  </p>
</li>
